### ISSUE TITLE
(TODO) generate an issue template

### ISSUE THREAD

**Issue by madguy02** [Rajan/lesspod#4]
**Description**: An issue template is required so that the person generating the issue have the idea of what are the information to be provided for the issue

**Comment by madguy02** [comment]
```
### Server Setup Information:

* Version of  Serverless component: 
* Operating System: 
* Deployment Method: 
* Node Version: 

### Steps to Reproduce:

1. <!-- First Step -->
2. <!-- Second Step -->
3. <!-- and so on... -->

### Expected behavior:

<!-- What you expect to happen -->

### Actual behavior:

<!-- What actually happens -->

### Relevant logs:
<!-- Logs from both server and browser -->
```
@Rajan  please check if this issue template works

**Comment by Rajan** [comment]
@madguy02 It sounds good. We can get started with it.

**Comment by Rajan** [comment]
We can add NPM version to this.

**Comment by Rajan** [comment]
@madguy02  It'd be great if you can create the template. Thanks.

**Comment by anurag-git** [comment]
### Issue Description:

###  Setup Information:

* Version of  Serverless component: 
* Operating System: 
* Deployment Method: 
* Node Version: 
* NPM Version:
* VueJS Version:

(Basically all details in package.json, better to uplaod package.json along with report).

### Steps to Reproduce:

1. 
2. 
3. 

### Probability of Occurence (Always, Rare, Intermittent):

### Probable Root Cause (if known): 

### Expected behavior (with screenshots, if possible):



### Actual behavior (with screenshots, if possible):



### Relevant logs (with screenshots, if possible):

**Comment by anurag-git** [comment]
Updated the template, @madguy02  @Rajan , Please have a look.
